---
version: '3.3'

services:
#  video_client:
#    container_name: video_client
#    build: src
#    command: sleep infinity
#    tty: true
#    stdin_open: true
#    volumes:
#       - ./dump:/tmp
#       - ./src:/src
#    networks:
#      media_server:
#        ipv4_address: 172.22.0.3

  video_server:
      container_name: video_server
      build: rtsp-server
      command: sleep infinity
      tty: true
      stdin_open: true
      volumes:
         - ./dump:/tmp
         - ./rtsp-server:/src
         - /videos/MX10_combined.ts:/videos/MX10_combined.ts
      environment:
        - TZ=America/Vancouver
        - DEBIAN_FRONTEND=noninteractive
      ports:
        - "8554:8554"
      networks:
        media_server:
          ipv4_address: 172.22.0.4

networks:
  media_server:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.22.0.0/24
